
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALLCOMMENTS BACKSLASHTRICKS EXP SMTHELSE STRINGexpression : STRINGexpression : BACKSLASHTRICKSexpression : EXPexpression : ALLCOMMENTSexpression : SMTHELSE\n    expression : expression expression\n    '
    
_lr_action_items = {'STRING':([0,1,2,3,4,5,6,7,],[2,2,-1,-2,-3,-4,-5,2,]),'BACKSLASHTRICKS':([0,1,2,3,4,5,6,7,],[3,3,-1,-2,-3,-4,-5,3,]),'EXP':([0,1,2,3,4,5,6,7,],[4,4,-1,-2,-3,-4,-5,4,]),'ALLCOMMENTS':([0,1,2,3,4,5,6,7,],[5,5,-1,-2,-3,-4,-5,5,]),'SMTHELSE':([0,1,2,3,4,5,6,7,],[6,6,-1,-2,-3,-4,-5,6,]),'$end':([1,2,3,4,5,6,7,],[0,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,7,],[1,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> STRING','expression',1,'p_expression_string','mainall.py',49),
  ('expression -> BACKSLASHTRICKS','expression',1,'p_expression_backslashtricks','mainall.py',53),
  ('expression -> EXP','expression',1,'p_expression_exp','mainall.py',57),
  ('expression -> ALLCOMMENTS','expression',1,'p_expression_allcomments','mainall.py',61),
  ('expression -> SMTHELSE','expression',1,'p_expression_SMTHELSE','mainall.py',65),
  ('expression -> expression expression','expression',2,'p_expression','mainall.py',71),
]
